DROP DATABASE IF EXISTS superhero;
CREATE DATABASE superhero;
USE superhero; 

CREATE TABLE City (
    CITY_ID int,
    CITY_NAME VARCHAR(255),
    PRIMARY KEY(CITY_ID)
);

CREATE TABLE Superhero (
    SUPERHERO_ID INT AUTO_INCREMENT,
    SUPERHERO_NAME VARCHAR(255) NOT NULL,
    REEL_NAME VARCHAR(255) NOT NULL,
    IS_HUMAN BOOLEAN,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    POWERLEVEL DECIMAL,
    CITY_ID INT,
    PRIMARY KEY(SUPERHERO_ID),
    FOREIGN KEY (CITY_ID) REFERENCES City(CITY_ID)
);


CREATE TABLE Superpower (
    SUPERPOWER_ID INT,
    SUPERPOWER_NAME VARCHAR(255),
    PRIMARY KEY(SUPERPOWER_ID)
);

CREATE TABLE SuperheroPower (
    SUPERHERO_ID int, 
    SUPERPOWER_ID int,
    FOREIGN KEY(SUPERHERO_ID) REFERENCES Superhero(SUPERHERO_ID),
    FOREIGN KEY(SUPERPOWER_ID) REFERENCES Superpower(SUPERPOWER_ID)
);
